export enum BlogsCategoriesEnum {
    PROJECTS = "PROJECTS",
    LOCAL_PRODUCTS = "LOCAL_PRODUCTS",
    SERVICES = "SERVICES",
    TOURIST_ATTRACTIONS = "TOURIST_ATTRACTIONS",
    PEOPLE_AND_VALUES = "PEOPLE_AND_VALUES",
    CALLS = "CALLS",
    EVENTS = "EVENTS",
    AGRICULTURE = "AGRICULTURE",
    TOURISM = "TOURISM",
    ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
    YOUTH = "YOUTH",
    CULTURE = "CULTURE",
    PUBLIC = "PUBLIC",
    ECOLOGY = "ECOLOGY",
    PARTNERSHIPS = "PARTNERSHIPS",
}

export enum BlogsContentTypeEnum {
    NEWS = "NEWS",
    PROJECT = "PROJECT",
    AUTHENTIC_LOCAL = "AUTHENTIC_LOCAL",
}

export enum AuthenticLocalCategoriesEnum {
    LOCAL_PRODUCTS = "LOCAL_PRODUCTS",
    SERVICES = "SERVICES",
    TOURIST_ATTRACTIONS = "TOURIST_ATTRACTIONS",
    PEOPLE_AND_VALUES = "PEOPLE_AND_VALUES",
}